// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package cache

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//Request to the get function of the Cache service.
type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{2}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{3}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UnsetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsetRequest) Reset()         { *m = UnsetRequest{} }
func (m *UnsetRequest) String() string { return proto.CompactTextString(m) }
func (*UnsetRequest) ProtoMessage()    {}
func (*UnsetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{4}
}

func (m *UnsetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsetRequest.Unmarshal(m, b)
}
func (m *UnsetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsetRequest.Marshal(b, m, deterministic)
}
func (m *UnsetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsetRequest.Merge(m, src)
}
func (m *UnsetRequest) XXX_Size() int {
	return xxx_messageInfo_UnsetRequest.Size(m)
}
func (m *UnsetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsetRequest proto.InternalMessageInfo

func (m *UnsetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UnsetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsetResponse) Reset()         { *m = UnsetResponse{} }
func (m *UnsetResponse) String() string { return proto.CompactTextString(m) }
func (*UnsetResponse) ProtoMessage()    {}
func (*UnsetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{5}
}

func (m *UnsetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsetResponse.Unmarshal(m, b)
}
func (m *UnsetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsetResponse.Marshal(b, m, deterministic)
}
func (m *UnsetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsetResponse.Merge(m, src)
}
func (m *UnsetResponse) XXX_Size() int {
	return xxx_messageInfo_UnsetResponse.Size(m)
}
func (m *UnsetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnsetResponse proto.InternalMessageInfo

func (m *UnsetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type FlushResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlushResponse) Reset()         { *m = FlushResponse{} }
func (m *FlushResponse) String() string { return proto.CompactTextString(m) }
func (*FlushResponse) ProtoMessage()    {}
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{6}
}

func (m *FlushResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlushResponse.Unmarshal(m, b)
}
func (m *FlushResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlushResponse.Marshal(b, m, deterministic)
}
func (m *FlushResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlushResponse.Merge(m, src)
}
func (m *FlushResponse) XXX_Size() int {
	return xxx_messageInfo_FlushResponse.Size(m)
}
func (m *FlushResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlushResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlushResponse proto.InternalMessageInfo

func (m *FlushResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "cache.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "cache.GetResponse")
	proto.RegisterType((*SetRequest)(nil), "cache.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "cache.SetResponse")
	proto.RegisterType((*UnsetRequest)(nil), "cache.UnsetRequest")
	proto.RegisterType((*UnsetResponse)(nil), "cache.UnsetResponse")
	proto.RegisterType((*FlushResponse)(nil), "cache.FlushResponse")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_5fca3b110c9bbf3a) }

var fileDescriptor_5fca3b110c9bbf3a = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xd7, 0x8e, 0x88, 0xfe, 0xdd, 0x44, 0xe3, 0x90, 0x51, 0xd1, 0x95, 0x78, 0xb3, 0xab,
	0x0c, 0x74, 0xe0, 0x03, 0x88, 0xee, 0xbe, 0xc1, 0x07, 0xd8, 0xc6, 0x71, 0x83, 0xd6, 0xa5, 0x9a,
	0x54, 0xd8, 0x8b, 0xfa, 0x3c, 0xd2, 0x64, 0xce, 0x96, 0xd1, 0xdd, 0x25, 0xe7, 0x7c, 0xff, 0xcf,
	0x39, 0xe7, 0x47, 0xb4, 0x9c, 0x2f, 0xd7, 0x24, 0x8b, 0x2f, 0x6d, 0x35, 0x67, 0xee, 0x13, 0xdf,
	0xac, 0xb4, 0x5e, 0xe5, 0x34, 0x71, 0xc5, 0x45, 0xf9, 0x3e, 0xa1, 0x8f, 0xc2, 0x6e, 0x3d, 0x23,
	0xee, 0x80, 0x19, 0xd9, 0x94, 0x3e, 0x4b, 0x32, 0x96, 0x5f, 0xa0, 0x9b, 0xd1, 0x76, 0x18, 0x24,
	0xc1, 0xf8, 0x2c, 0xad, 0x9e, 0xe2, 0x1e, 0x91, 0xeb, 0x9b, 0x42, 0x6f, 0x0c, 0xf1, 0x01, 0xd8,
	0xf7, 0x3c, 0x2f, 0x69, 0x18, 0x26, 0xc1, 0xb8, 0x97, 0xfa, 0x8f, 0x98, 0x02, 0xea, 0x88, 0x49,
	0x8b, 0xea, 0x16, 0x91, 0xaa, 0x59, 0x9f, 0x23, 0xd4, 0x99, 0x53, 0x9d, 0xa6, 0xa1, 0xce, 0x44,
	0x82, 0xde, 0xdb, 0xc6, 0x1c, 0x9b, 0x6d, 0x84, 0xfe, 0x8e, 0x68, 0xb1, 0x18, 0xa1, 0xff, 0x9a,
	0x97, 0x66, 0xdd, 0x06, 0x3c, 0xfc, 0x04, 0x60, 0xcf, 0xd5, 0x91, 0xb8, 0x44, 0x77, 0x46, 0x96,
	0x5f, 0x4a, 0x7f, 0xc0, 0xff, 0x9b, 0xc4, 0xbc, 0x5e, 0xf2, 0x3e, 0xa2, 0x53, 0xf1, 0xaa, 0xc6,
	0xab, 0x43, 0x5e, 0x35, 0xf8, 0x29, 0x98, 0x9b, 0x95, 0x5f, 0xed, 0xda, 0xf5, 0xdd, 0xe2, 0x41,
	0xb3, 0xb8, 0x57, 0x3d, 0x81, 0xb9, 0x05, 0xf8, 0xb5, 0xf4, 0x21, 0xca, 0xbf, 0x10, 0xe5, 0x4b,
	0x15, 0xe2, 0x5e, 0xd8, 0x58, 0x53, 0x74, 0x16, 0x27, 0x8e, 0x7b, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x9a, 0xbf, 0x6d, 0x10, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheClient is the client API for Cache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Unset(ctx context.Context, in *UnsetRequest, opts ...grpc.CallOption) (*UnsetResponse, error)
	Flush(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FlushResponse, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/cache.Cache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/cache.Cache/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Unset(ctx context.Context, in *UnsetRequest, opts ...grpc.CallOption) (*UnsetResponse, error) {
	out := new(UnsetResponse)
	err := c.cc.Invoke(ctx, "/cache.Cache/Unset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Flush(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FlushResponse, error) {
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, "/cache.Cache/Flush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServer is the server API for Cache service.
type CacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Unset(context.Context, *UnsetRequest) (*UnsetResponse, error)
	Flush(context.Context, *empty.Empty) (*FlushResponse, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.Cache/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Unset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Unset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.Cache/Unset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Unset(ctx, req.(*UnsetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.Cache/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Flush(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cache.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Cache_Set_Handler,
		},
		{
			MethodName: "Unset",
			Handler:    _Cache_Unset_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _Cache_Flush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}
